learning_templates/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

app_name = 'basicapp'

urlpatterns = [
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basicapp import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^basicapp/',include('basicapp.urls')),
    path('admin/', admin.site.urls),
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'basicapp/index.html')

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative_url_template.html')

learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

      </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
       <div class="container">
         <ul class="nav navbar-nav">
           <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
           <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
           <li><a class="navbar-link" href="{% url 'basicapp:other' %}">Other</a></li>
         </ul>
       </div>
     </nav>
     <div class="container">



     {% block body_block %}
     {# Anything outside of this will be inherited if you use extend.#}
     {% endblock %}
     </div>


  </body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block %}
  <h1>Welcome to index</h1>
      <h1>This is the index.html page</h1>
  {% endblock %}

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %}
  {% block body_block %}
  <h1>Welcome to other</h1>
  <h1>This is an example of template inheritance!</h1>
  {% endblock %}

learning_templates/templates/basicapp/relative_url_template.html
<html>
<head>
  <title></title>
</head>
<body>
  <h1>Welcome to relative url templates</h1>
  <a href="{% url 'basicapp:other' %}">THE OTHER PAGE</a>
  <a href="{% url 'admin:index' %}">ADMIN</a>
</body>
</html>